const production = { userName: localStorage.getItem('questlog-user-name') || '' };
function emptyState(icon, title, message, action, callback) { const box = document.createElement('div'); box.className = 'empty-state'; box.innerHTML = `<div class="empty-icon">${icon}</div><h3>${title}</h3><p>${message}</p><button class="primary">${action}</button>`; box.querySelector('button').addEventListener('click', callback); return box; }
function clearDemoContent() {
  document.querySelector('.now-playing')?.classList.add('clean-hide');
  const feed = document.querySelector('#activityFeed'); if (feed) { feed.replaceChildren(emptyState('◈', 'Your activity starts here', 'Add a game, log a session, or follow friends to build your feed.', 'Add your first game', () => document.querySelector('#gameDialog').showModal())); }
  document.querySelector('.rightbar')?.classList.add('clean-hide');
  const library = document.querySelector('#libraryGrid'); if (library) { library.replaceChildren(emptyState('▦', 'Your library is empty', 'Start with a game you own, are playing, or want to try.', 'Add a game', () => document.querySelector('#gameDialog').showModal())); }
  const recs = document.querySelector('#recommendations'); if (recs) recs.replaceChildren(emptyState('✦', 'Recommendations will appear here', 'Tell Questlog what you play and we’ll tailor this list to you.', 'Add a game', () => document.querySelector('#gameDialog').showModal()));
  const friends = document.querySelector('#friendsGrid'); if (friends) friends.replaceChildren(emptyState('♧', 'Find your people', 'Follow friends to see what they are playing and share your gaming life.', 'Find friends', () => document.querySelector('#findFriends')?.click()));
  document.querySelector('.friend-summary')?.classList.add('clean-hide'); document.querySelector('.free-plus-ad')?.remove();
  const log = document.querySelector('.profile-log'); if (log) log.replaceChildren(emptyState('◎', 'No sessions logged yet', 'Your recently played games will show up here.', 'Add a game', () => document.querySelector('#gameDialog').showModal()));
  document.querySelectorAll('.profile-stats strong').forEach(stat => stat.textContent = '0');
  document.querySelectorAll('.library-tabs b').forEach(count => count.textContent = '0');
}
function updateName(name) { const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode); nodes.forEach(node => { node.nodeValue = node.nodeValue.replace(/Preet|@preetplays/g, value => value.startsWith('@') ? `@${name.toLowerCase().replace(/\s+/g, '')}` : name); }); }
clearDemoContent(); if (production.userName) updateName(production.userName);
if (!localStorage.getItem('questlog-onboarded')) { const onboarding = document.createElement('dialog'); onboarding.className = 'onboarding'; onboarding.innerHTML = `<div class="onboarding-hero"><a class="brand"><span class="brand-mark">Q</span><span>questlog</span></a></div><form class="onboarding-content"><p class="eyebrow lime">WELCOME TO QUESTLOG</p><h2>Build your game life.</h2><p class="muted">Track your library, share what you’re playing, and find your next favourite.</p><label>What should we call you?<input name="name" required maxlength="24" placeholder="Your gamer name" autocomplete="nickname" /></label><button class="primary" type="submit">Start my Questlog →</button><div class="onboard-steps"><i></i><i></i><i></i></div></form>`; document.body.append(onboarding); onboarding.showModal(); onboarding.querySelector('form').addEventListener('submit', event => { event.preventDefault(); const name = new FormData(event.currentTarget).get('name').trim(); if (!name) return; localStorage.setItem('questlog-user-name', name); localStorage.setItem('questlog-onboarded', 'true'); updateName(name); onboarding.close(); }); }
const savedGames = [];
const escapeHtml = value => value.replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
document.querySelector('#saveGame')?.addEventListener('click', () => { const title = document.querySelector('#gameTitle').value.trim(); const status = document.querySelector('#gameStatus').value; if (!title) return; setTimeout(() => { savedGames.push({ title, status }); const library = document.querySelector('#libraryGrid'); library.innerHTML = savedGames.map(game => `<article class="game-tile"><div class="tile-art cyber">${escapeHtml(game.title.toUpperCase())}</div><div><strong>${escapeHtml(game.title)}</strong><small>${game.status}</small><span class="status">${game.status.toUpperCase()}</span></div></article>`).join(''); const feed = document.querySelector('#activityFeed'); feed.innerHTML = `<article class="activity"><span class="avatar me">P</span><div class="activity-body"><div class="activity-top"><strong>${escapeHtml(localStorage.getItem('questlog-user-name') || 'You')}</strong> added <strong>${escapeHtml(title)}</strong> to ${status.toLowerCase()} <span class="activity-time">just now</span></div></div></article>`; }, 0); });
